@BASE_URL_LOCAL = http://localhost:3030
@USER_ID = 68cc011ebc3c270f9afda563


# SignUp
POST {{BASE_URL_LOCAL}}/api/auth/signup
Content-Type: application/json

{
    "username": "jjj",
    "password": "111",
    "fullname": "d w"
}

###

# Login
POST {{BASE_URL_LOCAL}}/api/auth/login
Content-Type: application/json

{
    "username": "jjj",
    "password": "111"
}

###

# Logout
POST {{BASE_URL_LOCAL}}/api/auth/logout
Content-Type: application/json

{
    "username": "dandansss",
    "password": "111"
}

###

