@BASE_URL_LOCAL = http://localhost:3030
@USER_ID = 68c948b142ceebbfe8ea6987

# Get Users
GET {{BASE_URL_LOCAL}}/api/user

###

# Get User By Id

GET {{BASE_URL_LOCAL}}/api/user/{{USER_ID}}

###

# Update User

Put {{BASE_URL_LOCAL}}/api/user/{{USER_ID}}
Content-Type: application/json

{
 "_id": "{{USER_ID}}",
  "username": "vc",
  "fullname": "d w",
  "score": 600
}


###
# Remove User

Delete {{BASE_URL_LOCAL}}/api/user/{{USER_ID}}

###

# POST {{BASE_URL_LOCAL}}/api/user/
# Content-Type: application/json

# {
# "username": "user.username",
# "password": "user.password",
# "fullname": "user.fullname",
# "score": 0
# }

