
@BASE_URL_LOCAL = http://localhost:3030
@REQ_ID = 68ce5d1223069365a092c1b9
@TOY_ID = 68cd07002d586aa01791e133
@USER_ID = 68ce588b5c9d48e910e6d561


# Get Reviews
GET  {{BASE_URL_LOCAL}}/api/review/

###  



# Get Review By Id
# GET  {{BASE_URL_LOCAL}}/api/review/{{REQ_ID}}


#### 


# Post Review
POST   {{BASE_URL_LOCAL}}/api/review/
Content-Type: application/json 

{
 "aboutToyId": "68cd07002d586aa01791e133",
 "txt": "hole!"
}


###
# Delete Review

DELETE  {{BASE_URL_LOCAL}}/api/review/{{REQ_ID}}

###

