
@BASE_URL_LOCAL = http://localhost:3030
@REVIEW_ID = 68cd1c81d5f016f102fbb828


# Get Reviews
GET  {{BASE_URL_LOCAL}}/api/review

###  
# Get Review By Id

GET  {{BASE_URL_LOCAL}}/api/review/{{REVIEW_ID}}

### 

# Post Review
POST   {{BASE_URL_LOCAL}}/api/review/
Content-Type: application/json 

{
 "byUserId": "5b507e97f20dd52bb6e67a44",
 "toyId": "5b4f0b081043ae5f9cf3494c",
 "txt": "Best toy ever!"
}


###
# Delete Review

DELETE  {{BASE_URL_LOCAL}}/api/review/{{REVIEW_ID}}

###

